### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by AxelTerizaki** [mnyrop/pagemaster#14]
This is a weird issue maybe not related to pagemaster itself, but I'm not getting errors when using other plugins or even Jekyll himself to process it.

When I try to run pagemaster on a sample JSON I made, I get an invalid JSON error : 

```
$ bundle exec jekyll pagemaster karas_fr
Processing _data/karas_fr.json....
jekyll 3.8.3 | Error:  Cannot load _data/karas_fr.json. check for typos and rebuild.
```

Visual Studio Code reports no issues with my JSON file, I'm attaching it to this issue. (renamed to .txt so GitHub accepts it)

Here's my config file : 

```yaml
plugins:
  - pagemaster

collections:
  karas_fr:
    output: true
    source: karas_fr.json
    id_key: kid
    layout: kara_fr
```

[karas_fr.json.txt](https://github.com/mnyrop/pagemaster/files/2339246/karas_fr.json.txt)

I use this file as a collection already (it's in the _data directory) and Jekyll generates a single page as an index with every record in there without issue. 

My only lead is that the JSON is a "karas" array and pagemaster won't process it because it expects an array without a name, but I'm not even sure this is valid JSON... And doing so would keep Jekyll from generating an index page. I can access the collection through `site.data.karas_fr.karas` for example...
